title: Jessica Jalbert # your name (or website title) here
logo: "/images/IMG_6027[392] (2).jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Former Educator turned Data Analyst
  <br><br>
  book worm 📚 reality TV junkie 📺 major crafter 🧶
  <br><br>
  <a href="www.linkedin.com/in/jessjalbs">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
